<div class="w-full text-center overflow-hidden py-8 print:hidden">
	<p class="text-3xl">Loading...</p>
	<div class="loadingio-spinner-bars-segxihspibr">
		<!-- Based on code from https://loading.io/ -->
		<div class="ldio-ios8miac3yb">
			<div />
			<!-- Red -->
			<div />
			<!-- Orange -->
			<div />
			<!-- Yellow -->
			<div />
			<!-- Green -->
			<div />
			<!-- Blue -->
			<div />
			<!-- Indigo -->
			<div />
			<!-- Violet -->
		</div>
	</div>
</div>

<style>
	.loadingio-spinner-bars-segxihspibr {
		width: 100%;
		max-width: 242px;
		height: 100px;
		display: inline-block;
		overflow: hidden;
		background: none;
	}
	.ldio-ios8miac3yb {
		width: 100%;
		height: 100%;
		position: relative;
		transform: translateZ(0) scale(1);
		backface-visibility: hidden;
		transform-origin: 0 0;
	}
	@keyframes ldio-ios8miac3yb {
		0% {
			opacity: 1;
		}
		50% {
			opacity: 0.3;
		}
		100% {
			opacity: 1;
		}
	}
	.ldio-ios8miac3yb div {
		position: absolute;
		width: 20px;
		height: 80px;
		top: 20px;
		animation: ldio-ios8miac3yb 1.75s cubic-bezier(0.5, 0, 0.5, 1) infinite;
	}
	.ldio-ios8miac3yb div:nth-child(1) {
		transform: translate(0px, 0);
		background: #e94e59;
		animation-delay: -1.75s;
	}
	.ldio-ios8miac3yb div:nth-child(2) {
		transform: translate(37px, 0);
		background: #e97945;
		animation-delay: -1.5s;
	}
	.ldio-ios8miac3yb div:nth-child(3) {
		transform: translate(74px, 0);
		background: #e0d252;
		animation-delay: -1.25s;
	}
	.ldio-ios8miac3yb div:nth-child(4) {
		transform: translate(111px, 0);
		background: #43c263;
		animation-delay: -1s;
	}
	.ldio-ios8miac3yb div:nth-child(5) {
		transform: translate(148px, 0);
		background: #2891c2;
		animation-delay: -0.75s;
	}
	.ldio-ios8miac3yb div:nth-child(6) {
		transform: translate(185px, 0);
		background: #273aa7;
		animation-delay: -0.5s;
	}
	.ldio-ios8miac3yb div:nth-child(7) {
		transform: translate(222px, 0);
		background: #6630bd;
		animation-delay: -0.25s;
	}
	/* generated by https://loading.io/ then edited to add more bars*/
</style>
